"""Initial tables after reset

Revision ID: df0f5493e658
Revises: 
Create Date: 2025-08-06 12:04:23.980868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0f5493e658'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subscription_start', sa.Date(), nullable=False),
    sa.Column('subscription_end', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.String(length=50), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('wifi_ssid', sa.String(length=100), nullable=True),
    sa.Column('signal_strength', sa.Integer(), nullable=True),
    sa.Column('uptime', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('band_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('band')
    op.drop_table('shop')
    # ### end Alembic commands ###
